#!/usr/bin/env python
import rospy
from std_msgs.msg import String

class sensor_gps:
	def __init__(self):
		pass

if __name__ == '__main__':
    try:
        sensor_gps()
    except rospy.ROSInterruptException:
        pass